package com.catchmenearby.features.auth.ui;

import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;
import com.catchmenearby.MainActivity;
import com.catchmenearby.R; // This will be generated by the build process
import com.catchmenearby.features.auth.viewmodel.AuthViewModel;
import com.google.android.material.textfield.TextInputEditText;

public class LoginActivity extends AppCompatActivity {
    private AuthViewModel authViewModel;
    private TextInputEditText emailEditText, passwordEditText;
    private Button loginButton, goToSignUpButton;
    private TextView errorTextView;
    private ProgressBar progressBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Apply the theme if it's not set in AndroidManifest.xml for the activity
        // setTheme(R.style.Theme_CatchMeNearby);
        setContentView(R.layout.activity_login);

        authViewModel = new ViewModelProvider(this).get(AuthViewModel.class);

        emailEditText = findViewById(R.id.editTextEmail_login);
        passwordEditText = findViewById(R.id.editTextPassword_login);
        loginButton = findViewById(R.id.buttonLogin_login);
        goToSignUpButton = findViewById(R.id.buttonGoToSignUp_login);
        errorTextView = findViewById(R.id.textViewError_login);
        progressBar = findViewById(R.id.progressBar_login);

        authViewModel.getUserLiveData().observe(this, firebaseUser -> {
            if (firebaseUser != null) {
                // User is logged in, navigate to MainActivity
                Intent intent = new Intent(LoginActivity.this, MainActivity.class);
                intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(intent);
                finish(); // Finish LoginActivity
            }
        });

        authViewModel.getErrorMessageLiveData().observe(this, error -> {
            if (error != null && !error.isEmpty()) {
                errorTextView.setText(error);
                errorTextView.setVisibility(View.VISIBLE);
                // Toast.makeText(this, error, Toast.LENGTH_LONG).show(); // Can be too intrusive
            } else {
                errorTextView.setText("");
                errorTextView.setVisibility(View.GONE);
            }
        });

        authViewModel.getIsLoadingLiveData().observe(this, isLoading -> {
            if (isLoading != null && isLoading) {
                progressBar.setVisibility(View.VISIBLE);
                loginButton.setEnabled(false);
                goToSignUpButton.setEnabled(false);
            } else {
                progressBar.setVisibility(View.GONE);
                loginButton.setEnabled(true);
                goToSignUpButton.setEnabled(true);
            }
        });

        loginButton.setOnClickListener(v -> {
            String email = emailEditText.getText() != null ? emailEditText.getText().toString().trim() : "";
            String password = passwordEditText.getText() != null ? passwordEditText.getText().toString().trim() : "";

            if (email.isEmpty()) {
                emailEditText.setError("Email cannot be empty");
                emailEditText.requestFocus();
                return;
            }
            if (!android.util.Patterns.EMAIL_ADDRESS.matcher(email).matches()) {
                emailEditText.setError("Enter a valid email address");
                emailEditText.requestFocus();
                return;
            }
            if (password.isEmpty()) {
                passwordEditText.setError("Password cannot be empty");
                passwordEditText.requestFocus();
                return;
            }
            // Basic password length check (Firebase enforces minimum 6)
            if (password.length() < 6) {
                passwordEditText.setError("Password must be at least 6 characters");
                passwordEditText.requestFocus();
                return;
            }

            authViewModel.login(email, password);
        });

        goToSignUpButton.setOnClickListener(v -> {
            Intent intent = new Intent(LoginActivity.this, SignUpActivity.class);
            startActivity(intent);
        });
    }
}
