package com.catchmenearby.features.auth.ui;

import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;
import com.catchmenearby.MainActivity;
import com.catchmenearby.R; // This will be generated by the build process
import com.catchmenearby.features.auth.viewmodel.AuthViewModel;
import com.google.android.material.textfield.TextInputEditText;

public class SignUpActivity extends AppCompatActivity {
    private AuthViewModel authViewModel;
    private TextInputEditText emailEditText, passwordEditText;
    private Button signUpButton, goToLoginButton;
    private TextView errorTextView;
    private ProgressBar progressBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // setTheme(R.style.Theme_CatchMeNearby);
        setContentView(R.layout.activity_signup);

        authViewModel = new ViewModelProvider(this).get(AuthViewModel.class);

        emailEditText = findViewById(R.id.editTextEmail_signup);
        passwordEditText = findViewById(R.id.editTextPassword_signup);
        signUpButton = findViewById(R.id.buttonSignUp_signup);
        goToLoginButton = findViewById(R.id.buttonGoToLogin_signup);
        errorTextView = findViewById(R.id.textViewError_signup);
        progressBar = findViewById(R.id.progressBar_signup);

        authViewModel.getUserLiveData().observe(this, firebaseUser -> {
            if (firebaseUser != null) {
                // User is signed up and logged in, navigate to MainActivity
                Intent intent = new Intent(SignUpActivity.this, MainActivity.class);
                intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(intent);
                finishAffinity(); // Finish this activity and all parent activities (like LoginActivity if it's in stack)
            }
        });

        authViewModel.getErrorMessageLiveData().observe(this, error -> {
            if (error != null && !error.isEmpty()) {
                errorTextView.setText(error);
                errorTextView.setVisibility(View.VISIBLE);
            } else {
                errorTextView.setText("");
                errorTextView.setVisibility(View.GONE);
            }
        });

        authViewModel.getIsLoadingLiveData().observe(this, isLoading -> {
            if (isLoading != null && isLoading) {
                progressBar.setVisibility(View.VISIBLE);
                signUpButton.setEnabled(false);
                goToLoginButton.setEnabled(false);
            } else {
                progressBar.setVisibility(View.GONE);
                signUpButton.setEnabled(true);
                goToLoginButton.setEnabled(true);
            }
        });

        signUpButton.setOnClickListener(v -> {
            String email = emailEditText.getText() != null ? emailEditText.getText().toString().trim() : "";
            String password = passwordEditText.getText() != null ? passwordEditText.getText().toString().trim() : "";

            if (email.isEmpty()) {
                emailEditText.setError("Email cannot be empty");
                emailEditText.requestFocus();
                return;
            }
            if (!android.util.Patterns.EMAIL_ADDRESS.matcher(email).matches()) {
                emailEditText.setError("Enter a valid email address");
                emailEditText.requestFocus();
                return;
            }
            if (password.isEmpty()) {
                passwordEditText.setError("Password cannot be empty");
                passwordEditText.requestFocus();
                return;
            }
            if (password.length() < 6) { // Firebase min password length
                passwordEditText.setError("Password must be at least 6 characters");
                passwordEditText.requestFocus();
                return;
            }

            authViewModel.signUp(email, password);
        });

        goToLoginButton.setOnClickListener(v -> {
            // If LoginActivity is always the one starting SignUpActivity,
            // just finishing might be enough.
            // Or, ensure LoginActivity is started cleanly if it's not guaranteed to be in backstack.
            // For simplicity, just finish. If LoginActivity started it, it will show.
            finish();
            // Intent intent = new Intent(SignUpActivity.this, LoginActivity.class);
            // intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP); // Clears this from stack if Login is already there
            // startActivity(intent);
        });
    }
}
